# Generated by Django 6.0.2 on 2026-03-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('benchmark_score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='laptopspecs',
            name='processor_score',
        ),
        migrations.RemoveField(
            model_name='mobilespecs',
            name='processor_score',
        ),
        migrations.AddField(
            model_name='laptopspecs',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.processor'),
        ),
        migrations.AddField(
            model_name='mobilespecs',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.processor'),
        ),
    ]
