# Generated by Django 6.0.2 on 2026-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_processor_remove_laptopspecs_processor_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='antutu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='processor',
            name='geekbench_multi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processor',
            name='geekbench_single',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processor',
            name='benchmark_score',
            field=models.IntegerField(default=0),
        ),
    ]
