# Generated by Django 6.0.2 on 2026-03-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_processor_antutu_score_processor_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
