# Generated by Django 6.0.2 on 2026-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_processor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='slug',
        ),
    ]
