# Generated by Django 6.0.3 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_processor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='camera_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='performance_score',
            field=models.FloatField(default=0),
        ),
    ]
