# Generated by Django 6.0.3 on 2026-03-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart')], max_length=20, null=True),
        ),
    ]
