# Generated by Django 6.0.3 on 2026-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual_camera_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
