# Generated by Django 6.0.3 on 2026-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_manual_camera_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilespecs',
            name='charging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobilespecs',
            name='camera',
            field=models.CharField(max_length=100),
        ),
    ]
